### ISSUE TITLE
Cloth segmentation using U2-net model for Pytorch Live

### ISSUE THREAD

**Issue by lavandaboy** [raedle/UNetExample#1]
Hi @raedle,

Thanks for sharing the example for U2-net model. 

Now I am trying to implement [this](https://github.com/levindabhi/cloth-segmentation) model. It is based on U2-net but does the clothes segmentation. I also converted it into Pytorch Live. Here is the link (https://cdn-128.anonfiles.com/v5l75ez1yc/431fccf2-1658318807/cloth_segm_live.ptl) to the model. After changing the path from U2-net to this model I am trying to run everything. However, getting the "Error" alert. As I understand, the app drops after the following code:
`const rgbImage = oneDto3D(grayscaleTensor.mul(255));`

What do I need to change to make it work?

I will appreciate your help with this issue.

**Comment by raedle** [comment]
Hi @lavandaboy,

I can have a look. Can you try integrating your model into an Expo Snack to test it with the PlayTorch app? Details on the download and install are on https://playtorch.dev/

When you have the app installed, go the this u2net Snack to test the model from this repo: 

https://playtorch.dev/snack/@raedle/testing-u-net

When this works, try adding your cloth segmentation, and share that with me. I can then have a look.

**For context:**

PyTorch Live was renamed to PlayTorch today, and we provide easier tooling for people to build and share mobile ML experiences.

More details on the PlayTorch release: https://pytorch.org/blog/introducing-the-playtorch-app/

**Comment by lavandaboy** [comment]
Hi @raedle,

Huge news for PlayTorch community! Thanks a lot for your involvement in it! 

I have already played with every model during the weekend. I also tested your snack for U2-net, everything works for me.

[Here](https://snack.expo.dev/@lavandaboy/testing-u-net-cloth-segmentation) is the link to my expo snack for cloth segmentation model. Actually, I only changed the path to the model and did not do anything else :) However, I take a picture and nothing happens, I just see the camera UI.

I will heavily appreciate your help with this.

**Comment by raedle** [comment]
Thanks for the kind words, @lavandaboy!!

Would you mind filing an issue in the [facebookresearch/playtorch](https://github.com/facebookresearch/playtorch) repository with the *same* message that you posted 2 hours ago?

It will allow the rest of the PlayTorch team to investigate and offer help :)

Thank you!!˜
